- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: add repositories to apt
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main

- name: Install Tools
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - build-essential       #
    - tmux
    - vim
    - htop
    - git-core              #
    - wget
    - zlib1g-dev            #
    - libssl-dev            #
    - libreadline-dev       #
    - libyaml-dev           #
    - libxml2-dev           #
    - libxslt1-dev          #
    - libffi-dev            #
    - curl                  #
 #   - libcurl3
 #   - libcurl3-gnutls
    - libcurl4-openssl-dev
    - nodejs
    - software-properties-common
    - yarn
# These pkgs come from other roles: 
# - libsqlite3-dev
# - sqlite3 